"""model migration

Revision ID: c4b725ba9e80
Revises: 
Create Date: 2024-06-30 00:44:30.061599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b725ba9e80'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=True),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('received_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('index_from_email'), 'email', ['from_email'], unique=False)
    op.create_index(op.f('index_received_date'), 'email', ['received_date'], unique=False)
    op.create_index(op.f('index_to_email'), 'email', ['to_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_to_email'), table_name='email')
    op.drop_index(op.f('ix_email_received_date'), table_name='email')
    op.drop_index(op.f('ix_email_from_email'), table_name='email')
    op.drop_table('email')
    # ### end Alembic commands ###
